#!/bin/bash
#
# Taken from ArchLinux package "i3exit"

# take screenshot
#import -window root /tmp/screenshot.png

# blur it
#convert /tmp/screenshot.png -blur 0x10 -fill black -colorize 50% /tmp/screenshotblur.png
#rm /tmp/screenshot.png

# lock the screen
#i3lock -i /tmp/screenshotblur.png
i3lock -c 000000

exit 0
