#!/bin/zsh
main_term_open=$(xdotool search --name "main-term" | wc -l)

if [[ $main_term_open == 0 ]]; then
	alacritty -t 'main-term' -e tmux new-session -A -s main
fi
i3 '[title="^main-term$"] scratchpad show, resize set 95ppt 95ppt, move position center'

